authentication/urls.py
from django.urls import path
from authentication.views import login

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, increment, decrement, remove

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name="show_xml"),
    path('json/', show_json, name="show_json"),
    path('xml/<int:id>/', show_xml_by_id, name="show_xml_by_id"),
    path('json/<int:id>/', show_json_by_id, name="show_json_by_id"),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increment/<int:id>/', increment, name='increment'),
    path('decrement/<int:id>/', decrement, name='decrement'),
    path('remove/<int:id>/', remove, name='remove'),
]

authentication/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "description"]

class CustomRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)

main/views.py
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomRegistrationForm
from django.contrib.auth.models import User

@login_required(login_url='/login')
# Create your views here.
def show_main(request):
    products = Product.objects.filter(user=request.user)
    count = Product.objects.filter(user=request.user).count()
    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'products': products,
        'count': count,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = CustomRegistrationForm()

    if request.method == "POST":
        form = CustomRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increment(request, id):
    product = Product.objects.get(pk=id)
    product.amount += 1
    product.save()
    return HttpResponseRedirect('/')

def decrement(request, id):
    product = Product.objects.get(pk=id)
    product.amount = max(0, product.amount-1)
    product.save()
    return HttpResponseRedirect('/')

def remove(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    return HttpResponseRedirect('/')

main/templates/create_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css"></style>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% endblock meta %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="main.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fanwood+Text&family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    {% block content %}
    <body style="background-color: #FFF5E4;">
        <nav class="navbar navbar-dark" style="background-color: #FF9494;">
            <a class="navbar-brand" href="#" style="font-family: 'Prata', serif; font-size: x-large;">Inventory101</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            </div>
        </nav>

        <div class="login">
            <h1 style="text-align: center; font-family: 'Prata', serif; color: #1f130b; margin-top: 100px;">Add New Item</h1>
        </div>

        <div class="container">
            <form method="POST" action="" class="mx-auto">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleFormControlInput1">Name</label>
                    <input type="text" name="name" class="form-control" id="exampleFormControlInput1" placeholder="Enter item name">
                </div>

                <div class="form-outline">
                    <label for="typeNumber">Amount</label>
                    <input value="1" name="amount" type="number" id="typeNumber" class="form-control" />
                </div>

                <div class="form-outline mb-4">
                    <label class="form-label" for="form4Example3">Description</label>
                    <textarea class="form-control" name="description" ="form4Example3" rows="4" placeholder="Enter description"></textarea>
                </div>

                <button type ="submit" value="login" class="btn btn-primary" style="font-family: 'Prata', serif; background-color: #EE6983; border: 0;">
                    Add Item
                </button>
            </form>
        </div>

    {% endblock content %}

main/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css"></style>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% endblock meta %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="main.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fanwood+Text&family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    {% block content %}
    <body style="background-color: #FFF5E4;">
        <nav class="navbar navbar-dark" style="background-color: #FF9494;">
            <a class="navbar-brand" href="#" style="font-family: 'Prata', serif; font-size: x-large;">Inventory101</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            </div>
        </nav>

        <div class="login">
            <h1 style="text-align: center; font-family: 'Prata', serif; color: #1f130b; margin-top: 100px;">Login</h1>
        </div>

        <div class="container">
            <form method="POST" action="" class="mx-auto">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>

                <button type ="submit" value="login" class="btn btn-primary" style="font-family: 'Prata', serif; background-color: #EE6983; border: 0;">
                    Login
                </button>
            </form>

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert" style="margin-top: 20px;">
                    {{message}}
                </div>
                {% endfor %}
        {% endif %}

        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
    
    </div>
        </div>
        


        {% endblock content %}

main/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css">
            .github-link {
                color: inherit;
                text-decoration: none;
            }

            .github-link:hover {
                color: gray;
            }
        </style>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% endblock meta %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="main.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fanwood+Text&family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    {% block content %}
    <body style="background-color: #FFF5E4;">
        <nav class="navbar navbar-dark" style="background-color: #FF9494;">
            <a class="navbar-brand" href="#" style="font-family: 'Prata', serif; font-size: x-large;">Inventory101</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                <a class="nav-link" href="#" style="font-family: 'Prata', serif;">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}" style="font-family: 'Prata', serif;">Logout</a>
                </li>
            </ul>
            </div>
        </nav>

        <h1 style="text-align: center; font-family: 'Prata', serif; color: #1f130b; margin-top: 50px;">Welcome back, {{name}}!</h1>
        <h4 style="text-align: center; font-family: 'Prata', serif; color: #693008; margin-top: 20px;">There are currently {{count}} weapons in your inventory</h4>

        <div class="container">
            <div class="row">
                {% for product in products %}
                <div class="col-md-4">
                    <div class="card text-white" style="border-radius: 20px; background-color: #FFD1D1; border: 0; margin: 20px;">
                        <div class="card-body">
                            <h4 class="card-title" style="font-family: 'Prata', serif; color: #693008; font-weight: bolder;">{{product.name}}</h4>
                            <p class="card-text" style="font-family: 'Fanwood Text', serif; color: #8B4513">{{product.description}}</p>
                            <p class="card-text" style="font-family: 'Fanwood Text', serif; color: #1f130b"><small class="text-muted">Amount : {{product.amount}}</small></p>
                            <a href="{% url 'main:remove' product.id %}" class="btn btn-primary" style="background-color: #FF9494; border: 0; font-family: 'Prata'">Remove Item</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        
        <div class="d-flex justify-content-center">
            <a href="{% url 'main:create_product' %}">
                <button class="btn btn-primary btn-lg" style="font-family: 'Prata', serif; margin: 30px; background-color: #EE6983; border: 0;">
                    Add New Item
                </button>
            </a>
        </div>
        
        <footer class="text-center text-white" style="background-color: #FF9494">
            <!-- Grid container -->
            <div class="container">
                <hr class="my-5" />
        
              <!-- Section: Text -->
              <section class="mb-5">
                <div class="row d-flex justify-content-center">
                  <div class="col-lg-8">

                    <h4 style="font-family: 'Prata', serif; font-size: x-large;"">
                        <a href="#!" class="text-white">Inventory101</a>
                      </h4>
                    <h5 style="font-family: 'Fanwood Text', serif; margin-top: 20px;">
                      Bismillah nilai akhir PBP A. Aamiin.
                    </h5>

                    <a href="https://github.com/nabiilahputri13" target="_blank" class="github-link">
                        <i class="fab fa-github" style="font-size: 40px; margin-top: 20px;"></i>
                    </a>
                    
                    

                  </div>
                </div>
              </section>
              <!-- Section: Text -->
        
              <!-- Section: Social -->
            </div>
            <!-- Grid container -->
        
            <!-- Copyright -->
            <div
                 class="text-center p-3"
                 style="background-color: #EE6983"
                 >
              © 2023 Copyright:
              <a class="text-white"
                 >Nabiilah Putri Safa</a
                >
            </div>
            <!-- Copyright -->
          </footer>
        
        
        

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>


    {% endblock content %}

main/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css"></style>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {% endblock meta %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="main.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Fanwood+Text&family=Libre+Baskerville&family=Prata&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>

    {% block content %}
    <body style="background-color: #FFF5E4;">
        <nav class="navbar navbar-dark" style="background-color: #FF9494;">
            <a class="navbar-brand" href="#" style="font-family: 'Prata', serif; font-size: x-large;">Inventory101</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            </div>
        </nav>

        <div class="register">
            <h1 style="text-align: center; font-family: 'Prata', serif; color: #1f130b; margin-top: 100px;">Register</h1>
        </div>

        <div class="container">
            <form method="POST" action="" class="mx-auto">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username">
                    <small id="emailHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password1" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    <small id="emailHelp" class="form-text text-muted">
                        <ul>
                            <li>Your password can't be too similar to your other personal information.</li>
                            <li>Your password must contain at least 8 characters.</li>
                            <li>Your password can't be a commonly used password.</li>
                            <li>Your password can't be entirely numeric.</li>
                        </ul>
                    </small>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword2">Password confirmation</label>
                    <input type="password" name="password2" class="form-control" id="exampleInputPassword2" placeholder="Password">
                    <small id="emailHelp" class="form-text text-muted">Enter the same password as before, for verification.</small>
                </div>

                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success" role="alert" style="margin-top: 20px;">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}

                <button type ="submit" value="Daftar" class="btn btn-primary" style="font-family: 'Prata', serif; background-color: #EE6983; border: 0;">
                    Register
                </button>
            </form>
        </div>
    </body>

        
    {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <style type="text/css">
        </style>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% endblock meta %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    

    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>